### ISSUE TITLE
Cannot download data from sharepoint.

### ISSUE THREAD

**Issue by applezhao** [xjqicuhk/3DGNN#4]
Hi,
Has anyone downloaded data from sharepoint? If so, would u pls show me how?
I always got the error msg as "We're sorry, but ***@outlook.com can't be found in the mycuhk-my.sharepoint.com directory."

Apple

**Comment by xjqicuhk** [comment]
We have updated the download link to public access. Please try again.

**Comment by alexanderlarin** [comment]
And now all links are forbidden

**Comment by xjqicuhk** [comment]
Please download it from
https://drive.google.com/open?id=1AqQA-ipfc80caklR9kyUxunycrZjg7T2
